class Material(object):
    METAL = "metal"
    STONE = "stone"
    DIRT = "dirt"
    WOOD = "wood"
    LEATHER = "leather"
    SKIN = "skin"
    PLASTIC = "plastic"
    PAPER = "paper"
    CARDBOARD = "cardboard"
    GLASS = "glass"
    WATER = "water"
    MEAT = "meat"
    BREAD = "bread"
    CHEESE = "cheese"
